name: todo-app # This sets the name of the application (though name isn't officially part of the Docker Compose specification, it’s often used for organizational purposes).

nginx:
    image: nginx:1.17  # Using the Nginx image version 1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount the custom Nginx config file
    ports:
      - 8000:80  # Map port 80 of the container to port 8000 on the host machine
    depends_on:
      - backend  # Ensure backend service is up before Nginx starts
      - frontend  # Ensure frontend service is up before Nginx starts

frontend:
    image: "node:22"  # Use Node.js version 22 image
    user: "node"  # Run as non-root 'node' user inside the container
    working_dir: /home/node/app  # Set the working directory inside the container
    environment:
      - NODE_ENV=development  # Set the environment variable for development mode
      - WDS_SOCKET_PORT=0  # Disable WebSocket for the development server
    volumes:
      - ./frontend/:/home/node/app  # Mount the local frontend directory to the container's working directory
    expose:
      - "3000"  # Expose port 3000 inside the container (accessible by other services)
    ports:
      - "3000:3000"  # Map port 3000 of the container to port 3000 on the host machine
    command: "npm start"  # Command to start the frontend application

backend:
    image: todo-app/backend  # Custom image for backend (build from local directory)
    build: ./backend  # Build the backend from the local 'backend' directory
    volumes:
      - ./backend/:/usr/src/app  # Mount the local backend directory to the container's directory
    expose:
      - "3001"  # Expose port 3001 inside the container
    ports:
      - "8001:3001"  # Map container's port 3001 to host machine's port 8001
    command: "python src/server.py"  # Command to run the backend server
    environment:
      - DEBUG=true  # Set environment variable for debugging
    env_file:
      - path: ./.env  # Load environment variables from the .env file (required)
